[tool.poetry]
name = "face_alignment_job"
version = "0.2.0"
description = "Face alignment & expression extraction job using SPECTRE"
authors = ["Viktor Vilskyi <viktor.vilskyi@gmail.com>"]
packages = [{ include = "face_alignment_job" }]

[tool.poetry.dependencies]
python = ">=3.9,<3.10"
google-cloud-storage = "^2.18.2"
tqdm = "^4.66.0"
numpy = "1.23.5"
opencv-python-headless = "^4.8.1.78"
Pillow = "^10.4.0"
trimesh = "^4.4.0"
scipy = "^1.11.0"
yacs = "^0.1.8"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"