[tool.poetry]
name = "avatar-dwpose-job"
version = "0.1.0"
description = "Runs DWPose to extract keypoints for AI avatars"
authors = ["Viktor Vilskyi <viktor.vilskyi@gmail.com>"]
packages = [{ include = "avatar_pose_job" }]

[tool.poetry.dependencies]
python = ">=3.11,<3.12"
google-cloud-storage = "^2.18.0"
numpy = "<2"
matplotlib = "3.6.2"
opencv-python = ">=4.8.0,<5.0.0"
scipy = "1.11.4"
scikit-image = "0.19.3"
huggingface-hub = "0.20.1"
dwpose = "^1.0.1"

[build-system]
requires = ["poetry-core>=1.9"]
build-backend = "poetry.core.masonry.api"